config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}

  root 'welcome#index'
  get 'error_test' => 'welcome#error_test'

  namespace :admin do
    get '/' => 'talents_manager#index'

    get 'talents_manager' => 'talents_manager#index'

    resources :candidates do
      get 'search', on: :collection
      resource :notifications
    end

    resources :interviewers do
      get 'search', on: :collection
      post 'delete_avatar'
    end

    resources :locations
    resources :location_sites

    get 'interview_events/new'
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :candidates, inverse_of: :location, class_name: "Admin::Candidate"
  has_many :sites, dependent: :destroy, class_name: "Admin::LocationSite"

  accepts_nested_attributes_for :sites

  validates :city, presence: true
  validates :description, presence: true
  validates :street_address, presence: true
  validate  :state_or_country_present

  def display_name
    dn = city + ", "
    dn += state.present? ? state : country
  end

  def full_address
    full_address = street_address + ", " + city + ", "
    full_address +=  state + " " if state
    full_address += zip if zip
  end

  private
  def state_or_country_present
    unless (state.present? || country.present?)
      errors.add(:state, "state or country required") unless state.present?
      errors.add(:country, "") unless country.present?
    end
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::AdminController
  before_action :set_admin_location, only: [:show, :edit, :update, :destroy]
  before_action :set_breadcrumbs, except: :index

  def index
    @locations = Location.order('id').all
  end

  def show
  end

  def edit
  end

  def update
    @admin_location.update!(admin_location_params)
    redirect_to admin_locations_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_location
      @admin_location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_location_params
      sites_attributes = [:id, :site_name, :site_url, :site_image, :description]
      params.require(:location).permit(:street_address, :city, :state, :zip, :country, :header, :description, {sites_attributes: sites_attributes})
    end

    def set_breadcrumbs
      super
      self.add_breadcrumb "Locations", :admin_locations_path
    end
end

app/views/admin/locations/_form.html.erb
<%= form_for admin_location, url: admin_location_path, name: "cadidate_schedule" do |f| %>
  <fieldset>
    <legend>Address Information</legend>
    <ol>
      <li>
        <%= f.text_field :street_address, class: "med-text-field", placeholder: "Address" %>
      </li>
      <li>
        <%= f.text_field :city, class: "med-text-field", placeholder: "City" %>
      </li>
      <li>
        <%# <input class="small-text-field" id="fName" name="fName" type="text" placeholder="State"> %>
        <%= f.collection_select :state, us_states, :last, :first, {selected: f.object.state} %>
        <%= f.text_field :zip, class: "small-text-field", placeholder: "Zip Code" %>
      </li>
      <li>
        <%= f.collection_select :country, only_rosetta_countries, :first, :last, {selected: f.object.country} %>
      </li>
    </ol>
  </fieldset>

  <fieldset>
    <legend>Location Header</legend>
    <ol>
      <li>
        <%= f.text_field :header, class: "med-text-field", placeholder: "" %>
      </li>
    </ol>
  </fieldset>

  <fieldset>
    <legend>Description</legend>
    <ol>
      <li>
        <%= f.cktext_area :description, id: "candidateContent", class: "text-area-field", placeholder: "" %>
      </li>
    </ol>
  </fieldset>

  <fieldset>
    <fieldset>
      <legend>Things to do in town:</legend>

      <ol>
        <%= f.fields_for :sites, admin_location.sites.all do |fi| %>
          <%= render partial: 'location_site', locals: {:f => fi} %>
        <% end %>
      </ol>
    </fieldset>

    <div class="button-bar">
      <%= button_tag "Cancel", type: 'button', class: "btn cancel-btn cancel_location", onclick: "javascript: window.location=\"#{admin_locations_path}\";" %>
      <%= f.submit "Save", class: "btn save-btn" %>
    </div>

  </fieldset>
<% end %>

app/views/admin/locations/_location_block.html.erb
<div class="box">
  <a href="<%= edit_admin_location_path(location_block) %>">
    <%= location_block.city %>, <%= location_city_or_country(location_block) %>
  </a>
</div>

app/views/admin/locations/_location_site.html.erb
<li>
  <%= image_tag f.object.site_image.thumb.url %>
</li>
<li>
  <%= f.text_field :site_name, class: "med-text-field", placeholder: "Title" %>
</li>
<li>
  <%= f.text_field :site_url, class: "med-text-field", placeholder: "Link" %>
</li>
<li>
  <%= f.text_field :description, class: "med-text-field", placeholder: "Description" %>
</li>
<li>
  <%= f.file_field :site_image, class: "med-text-field", placeholder: "Image" %>
</li>

app/views/admin/locations/edit.html.erb
<% content_for :view_styles  do -%>
  <%= stylesheet_link_tag "rs-admin-pages" %>
  <%= stylesheet_link_tag "rs-forms" %>
<% end -%>

<div class="main-container">
  <h1 class="header-text ">Location</h1>

  <%= render partial: "form", locals: {admin_location: @admin_location} %>

</div>

app/views/admin/locations/index.html.erb
<% content_for :view_styles  do -%>
  <%= stylesheet_link_tag "rs-admin-pages" %>
  <%= stylesheet_link_tag "rs-forms" %>
<% end -%>

<div class='locations-container'>
  <h1 class='header-text'>Manage Location Information</h1>

  <% @locations.in_groups_of(3, false) do |three_locations| %>
    <div class="box-wrapper">
      <%= render partial: "location_block", collection: three_locations %>
    </div>
  <% end %>
</div>

app/views/admin/locations/show.html.erb
<%= button_to "Edit", {action: "edit"}, method: :get %>

<h2>About <%= @admin_location.city %></h2>

<div>
  <p><%= @admin_location.description %></p>
</div>

<h4>Things to do in town:</h4>
<ul>
  <%= render partial: 'admin/candidates/location_site', collection: @admin_location.sites %>
</ul>