config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}

  root 'welcome#index'
  get 'error_test' => 'welcome#error_test'

  namespace :admin do
    get '/' => 'talents_manager#index'

    get 'talents_manager' => 'talents_manager#index'

    resources :candidates do
      get 'search', on: :collection
      resource :notifications
    end

    resources :interviewers do
      get 'search', on: :collection
      post 'delete_avatar'
    end

    resources :locations
    resources :location_sites

    get 'interview_events/new'
  end

end

app/controllers/admin/talents_manager_controller.rb
class Admin::TalentsManagerController < Admin::AdminController
  def index
  end
end

app/views/admin/talents_manager/index.html.erb
<% content_for :view_styles  do -%>
  <%= stylesheet_link_tag "rs-manager" %>
<% end -%>

<div class="manager-main">
  <div id="navcontainer">
    <div class="box-wrapper">
      <div class="box">
        <%= link_to admin_candidates_path do %>
          <img src="<%= image_path "sectionIcon1.png" %>" alt=""><br>
          Manage Candidates
        <% end %>
      </div>
      <div class="box">
        <%= link_to admin_locations_path do %>
          <img src="<%= image_path "sectionIcon2.png" %>" alt=""><br>
          Manage Location Information
        <% end %>
      </div>
      <div class="box">
        <%= link_to admin_interviewers_path do %>
          <img src="<%= image_path "sectionIcon3.png" %>" alt=""><br>
          Manage Interviewers
        <% end %>
      </div>
    </div>
  </div>
</div>