config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}

  root 'welcome#index'
  get 'error_test' => 'welcome#error_test'

  namespace :admin do
    get '/' => 'talents_manager#index'

    get 'talents_manager' => 'talents_manager#index'

    resources :candidates do
      get 'search', on: :collection
      resource :notifications
    end

    resources :interviewers do
      get 'search', on: :collection
      post 'delete_avatar'
    end

    resources :locations
    resources :location_sites

    get 'interview_events/new'
  end

end

app/models/admin/candidate.rb
class Admin::Candidate < ActiveRecord::Base
  enum publication_state: [:in_progress, :published, :on_hold]
  after_initialize :set_publication_state, :if => :new_record?

  belongs_to :user
  belongs_to :location, inverse_of: :candidates
  belongs_to :contact, class_name: "Admin::Contact"
  has_one    :interview, inverse_of: :candidate, class_name: "Admin::Interview"

  accepts_nested_attributes_for :contact
  accepts_nested_attributes_for :interview

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  # validates :greeting, presence: true
  # validates :title, presence: true
  validates :message, presence: {message: "Content for Candidate's page is required"}
  validates :location, presence: true
  validates :publication_state, presence: true
  validate :user_has_email

  def email
    return user.email if user.present?
    return nil
  end
  def email=(email)
    self.user.update!(email: email) if user.present?
  end


  def meet_with_interviewers
    self.interview.interview_events.map {|ie| ie.interviewers.all }.
      flatten.uniq.sort {|a,b| a.last_name <=> b.last_name}
  end

  def display_name
    first_name + " " + last_name
  end


  private
  def set_publication_state
    self.publication_state ||= :in_progress
  end

  def user_has_email
    if user && user.email.blank?
      errors.add(:email, "is required")
    end
  end
end

app/models/admin/interview_event.rb
class Admin::InterviewEvent < ActiveRecord::Base
  belongs_to :interview, class_name: "Admin::Interview"
  has_many :events_interviewers, foreign_key: :admin_interview_event_id, class_name: "Admin::EventsInterviewers"
  has_many :interviewers, through: :events_interviewers, class_name: "Admin::Interviewer"
end

app/controllers/admin/candidates_controller.rb
class Admin::CandidatesController < Admin::AdminController
  before_action :set_breadcrumbs, except: :show

  def index
    @candidates = Admin::Candidate.includes(:interview).order('id')
  end

  def show
    @candidate = Admin::Candidate.includes({interview: :interview_events}).find(params[:id])
    render "/welcome/index", layout: 'application'
  end

  def new
    @candidate = Admin::Candidate.new
    @candidate.contact = Admin::Contact.new
    @candidate.interview = Admin::Interview.new(interview_events: [Admin::InterviewEvent.new])
  end

  def create
    begin
      ActiveRecord::Base.transaction do
        @candidate = Admin::Candidate.new(candidate_params)
        contact_params = candidate_params[:contact_attributes]
        contact = Admin::Contact.where(email: contact_params[:email], last_name: contact_params[:last_name]).first
        unless contact.blank?
          @candidate.contact = contact
          candidate_params.delete(:contact_attributes)
        end

        if @candidate.save
          interview_date = params[:admin_candidate].fetch(:interview_attributes, {}).fetch(:interview_date, nil)
          unless interview_date.blank?
            @candidate.interview.update!(interview_date: Date.strptime(interview_date, "%m/%d/%Y"))
          end

          Admin::UserForCandidate.create_user_for(@candidate, params[:admin_candidate][:email])
          redirect_to admin_candidates_path, notice: "Candidate #{@candidate.first_name} #{@candidate.last_name} created"
        else
          render :new
        end
      end
    rescue ActiveRecord::ActiveRecordError, ApplicationError => error
      flash[:alert] = "Error: #{error.message}"
      render :new
    end
  end

  def edit
    @candidate = Admin::Candidate.includes({interview: {interview_events: :interviewers}}).find(params[:id])
  end

  def update
    @candidate = Admin::Candidate.includes({interview: {interview_events: :interviewers}}).find(params[:id])
    begin
      ActiveRecord::Base.transaction do
        @candidate.update!(candidate_params)

        interview_date = params[:admin_candidate].fetch(:interview_attributes, {}).fetch(:interview_date, nil)
        unless interview_date.blank?
          @candidate.interview.update!(interview_date: Date.strptime(interview_date, "%m/%d/%Y"))
        end
        redirect_to admin_candidates_path, notice: "Candidate #{@candidate.first_name} #{@candidate.last_name} updated"
      end
    rescue ActiveRecord::ActiveRecordError, ApplicationError => error
      flash[:alert] = "Error: #{error.message}"
      render :edit
    end
  end


  def search
    @candidates = Admin::Candidate.where('first_name like (:search_term) or last_name like (:search_term)', :search_term => "%#{params[:search]}%")

    respond_to do |format|
      format.js   # just renders candidates/search.js.erb
    end
  end

  private
    def candidate_params
      contact_attributes = [:id, :first_name, :last_name, :job_title, :email, :phone_number]
      interview_events_attributes = [:id, :event_name, :description, :location, {:interviewer_ids => []}, :event_begin, :event_end]
      interview_attributes = [:id, {interview_events_attributes: interview_events_attributes}]
      params.require(:admin_candidate).permit(:first_name, :last_name, :email, :phone_number,
                                              :greeting, :title, :message, :location_id,
                                              :contact_attributes => contact_attributes,
                                              :interview_attributes => interview_attributes)
    end

    def set_breadcrumbs
      super
      self.add_breadcrumb "Candidate", :admin_candidates_path
    end
end

app/views/admin/candidates/_candidate.html.erb
<!-- TODO: Need a helper for the email column -->
<tr>
  <td><%= candidate.updated_at.to_datetime.strftime("%D") %> UTC</td>
  <td><%= candidate.last_name %></td>
  <td><%= candidate.first_name %></td>
  <td><%= candidate.interview.interview_date %></td>
  <td><%= link_to "Email", new_admin_candidate_notifications_path(candidate) %></td>
  <td><%= candidate.publication_state.humanize %></td>
  <td><%= link_to "Edit", edit_admin_candidate_path(candidate) %></td>
  <td><%= link_to "View", admin_candidate_path(candidate) %></td>
</tr>

app/views/admin/candidates/_contact_fields.html.erb
<li>
  <%= f.text_field :first_name, class: "small-text-field", placeholder: "First Name" %>
  <%= f.text_field :last_name, class: "small-text-field", placeholder: "Last Name" %>
</li>
<li>
  <%= f.text_field :job_title, class: "med-text-field", placeholder: "Job Title" %>
</li>
<li>
  <%= f.text_field :email, class:"med-text-field", placeholder: "Email Address" %>
</li>
<li>
  <%= f.phone_field :phone_number, class: "med-text-field", placeholder: "Phone Number" %>
</li>

app/views/admin/candidates/_form.html.erb
<%= form_for candidate, html: {name: "cadidate_schedule", id: "candidate_form"} do |f| %>
  <fieldset>
    <legend>Name and Contact info</legend>
    <ol>
      <li>
        <%= f.text_field :first_name, class: "small-text-field", placeholder: "First Name" %>
        <%= f.text_field :last_name, class: "small-text-field", placeholder: "Last Name" %>
      </li>
      <li>
        <%= f.text_field :email, class: "med-text-field", placeholder: "Email Address", required: true %>
      </li>
      <li>
        <%= f.phone_field :phone_number, class: "med-text-field", placeholder: "Phone Number" %>
      </li>
    </ol>
  </fieldset>

  <fieldset>
    <legend>Content for Candidate's Page</legend>
    <ol>
      <li>
        <%= f.cktext_area :message, id: "candidateContent", class: "text-area-field", placeholder: "" %>
      </li>
      <li>
        <%= f.collection_select(:location_id, Location.order('id').all, :id, :display_name,
                                {prompt: "Select the office location"}, {required: "required"}) %>
      </li>
    </ol>
  </fieldset>

  <fieldset>
    <legend>Contact upon arrival</legend>
    <%= f.fields_for :contact do |builder| %>
      <ol>
        <%= render "contact_fields", :f => builder %>
      </ol>
    <% end %>
  </fieldset>

  <fieldset id="interviewSchedule">
    <%= f.fields_for :interview do |fi| %>
      <legend>Schedule for Interview</legend>
      <p>
        <%= fi.text_field :interview_date, id: "eventDate", placeholder: "Interview Date", readonly: true, value: short_date(f.object.interview.interview_date) %>
      </p>

      <ol id="interview_events">
        <%= render partial: "interview_event", locals: {f: fi} %>
      </ol>
    <% end %>
    <%= link_to "Add", admin_interview_events_new_path, remote: true, id: "add_interview_event_fields" %>
  </fieldset>

  <div class="button-bar">
    <%= f.submit "Cancel", type: "reset", class: "btn cancel-btn", onclick: "window.location=\'#{admin_candidates_path}\';return false;" %>
    <%= f.submit "Save", class: "btn save-btn" %>
  </div>
<% end %>





  <%# <h2>Content for Candidate's Page</h2> %>

  <%# <div><%= f.label :greeting %1><br /> %>
  <%# <%= f.text_field :greeting %1></div> %>

  <%# <div><%= f.label :title %1><br /> %>
  <%# <%= f.text_field :title %1></div> %>


  <%# <h3>Schedule for Interview</h3> %>

  <%# <%= f.fields_for :interview do |fi| %1> %>
  <%#   <div><%= fi.label :interview_date %1><br /> %>
  <%#     <%= fi.text_field :interview_date, {class: "datepicker", readonly: true} %1></div><br /> %>

  <%#   <div id="interview_events"> %>
  <%#     <%= render partial: "interview_event", locals: {f: fi} %1> %>
  <%#   </div> %>

  <%#   <div id="add_interview_event_fields"> %>
  <%#     <%= link_to "Create New Event", admin_interview_events_new_path, remote: true %1> %>
  <%#   </div> %>
  <%# <% end %1> %>

  <%# <br><br> %>
  <%# <div> %>
  <%#   <%= f.submit "Discard", type: "reset" %1> %>
  <%#   <%= f.submit "Save" %1> %>
  <%# </div> %>

app/views/admin/candidates/_interview_event.html.erb
<%= f.fields_for :interview_events do |f| %>
  <fieldset class="eventItem">
    <li>
      <%= f.text_field :event_name, class: "med-text-field", placeholder: "Title" %>
    </li>

    <li>
      <%= f.text_field :description, class: "med-text-field", placeholder: "Description" %>
    </li>

    <li>
      <%= f.text_field :location, class: "med-text-field", placeholder: "Location" %>
    </li>

    <li>
      <%= f.collection_select(:interviewer_ids, Admin::Interviewer.order('last_name').all,
                              :id, :display_name, {},
                              {multiple: true,
                               :"data-placeholder" => "Select Interviewers",
                               style: "width: 300px", class: "fancyselect"}) %>
    </li>

    <li>
      <%= f.text_field :event_begin, id: "eventStartTm", class: "small-text-field time-field ui-timepicker-input", placeholder: "Start Time", autocomplete: "off", value: absolute_time(f.object.event_begin) %>

      <%= f.text_field :event_end, id: "eventEndTm", class: "small-text-field time-field ui-timepicker-input", placeholder: "End Time", autocomplete: "off", value: absolute_time(f.object.event_end) %>
    </li>

    <% if f.object.new_record? %>
      <li>
        <%= link_to "Remove", "#", class: "remove_event" %>
      </li>
    <% end %>
  </fieldset>
<% end %>

app/views/admin/candidates/_location_site.html.erb
<li>
  <span>img</span>
  <span><%= location_site.site_name %>
</li>

app/views/admin/candidates/_meet_with_interviewer.html.erb
<li>
  <%= meet_with_interviewer.display_name %>
</li>

app/views/admin/candidates/_scheduled_event.html.erb
<tr>
  <td><%= scheduled_event.event_begin %></td>
  <td><%= scheduled_event.event_name %></td>
</tr>

app/views/admin/candidates/edit.html.erb
<% content_for :view_styles  do -%>
  <%= stylesheet_link_tag "rs-admin-pages" %>
  <%= stylesheet_link_tag "rs-forms" %>
<% end -%>

<div class="main-container">
  <h1 class="header-text ">Edit Candidate</h1>

  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
        <% @candidate.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render partial: "form", locals: {candidate: @candidate} %>
</div>

app/views/admin/candidates/index.html.erb
<% content_for :view_styles  do -%>
  <%= stylesheet_link_tag "rs-admin-pages" %>
  <%= stylesheet_link_tag "rs-forms" %>
<% end -%>

<div class="main-container">
  <h1 class="header-text ">Manage Candidates</h1>

  <div class='cf'>
    <div class='search-bar'>
      <%= form_tag(search_admin_candidates_url, method: "get", id: "candidatesearch", remote: true) do %>
        <%= text_field_tag :search, params[:name], placeholder: "Name", class:"small-text-field" %>
        <%= submit_tag "Search", :name => nil, class:"btn save-btn" %>
      <% end %>
    </div>
    <div class='create-new-bar'>
      <%= button_to "Create New Candidate", {action: "new"}, method: :get, class:'btn save-btn' %>
    </div>
  </div>

  <div id="candidateslist" class="cf">
    <table border="0" cellspacing="5" cellpadding="5">
      <thead>
        <tr>
          <th>Last Edited</th>
          <th>Last Name</th>
          <th>First Name</th>
          <th>Interview Date</th>
          <th>Email</th>
          <th>Candidates Page</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "candidate", collection: @candidates %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/candidates/new.html.erb
<% content_for :view_styles  do -%>
  <%= stylesheet_link_tag "rs-admin-pages" %>
  <%= stylesheet_link_tag "rs-forms" %>
<% end -%>

<div class="main-container">
  <h1 class="header-text">New Candidate</h1>

  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
        <% @candidate.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render partial: "form", locals: {candidate: @candidate} %>
</div>

app/views/admin/candidates/search.js.erb
$('#candidateslist tbody tr').remove();
$('#candidateslist tbody').append('<%=j render partial: "candidate", collection: @candidates %>');

app/views/admin/candidates/show.html.erb
<div>
  <div style="width: auto; float: left;">Last Published: <span class="date-local"><%= @candidate.updated_at.iso8601 %></span></div>
  <div style="width: auto; float: right;"><%= link_to "Back", :back %></div>
</div>

<div>
  <h1><%#= @candidate.greeting %> <%= @candidate.first_name %></h1>

  <h3><%= @candidate.title %></h3>

  <div><%= @candidate.message %></div>

  <div style="width: 400px; height: 300px; border: solid 1px black; margin: auto; margin-top: 1em; ">
    Video block here
  </div>

  <h4>Interview Schedule</h4>
  <h5><%= @candidate.interview.interview_date %></h5>
  <table border="0" cellspacing="5" cellpadding="5">
    <thead></thead>
    <tbody>
      <%= render partial: 'scheduled_event', collection: @candidate.interview.interview_events %>
    </tbody>
  </table>

  <h4>People you will meet:</h4>
  <ul>
    <%= render partial: 'meet_with_interviewer', collection: @candidate.meet_with_interviewers %>
  </ul>

  <h4>About <%= @candidate.location.city %></h4>
  <div><%= @candidate.location.description %></div>

  <h4>Things to do in town:</h4>
  <ul>
    <%= render partial: 'location_site', collection: @candidate.location.sites %>
  </ul>
</div>