config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}

  root 'welcome#index'
  get 'error_test' => 'welcome#error_test'

  namespace :admin do
    get '/' => 'talents_manager#index'

    get 'talents_manager' => 'talents_manager#index'

    resources :candidates do
      get 'search', on: :collection
      resource :notifications
    end

    resources :interviewers do
      get 'search', on: :collection
      post 'delete_avatar'
    end

    resources :locations
    resources :location_sites

    get 'interview_events/new'
  end

end

app/models/admin/location_site.rb
class Admin::LocationSite < ActiveRecord::Base
  mount_uploader :site_image, SiteImageUploader

  belongs_to :location
end

app/controllers/admin/location_sites_controller.rb
class Admin::LocationSitesController < Admin::AdminController
  before_action :set_admin_location_site, only: [:show, :edit, :update, :destroy]

  # GET /admin/location_sites
  # GET /admin/location_sites.json
  def index
    @admin_location_sites = Admin::LocationSite.all
  end

  # GET /admin/location_sites/1
  # GET /admin/location_sites/1.json
  def show
  end

  # GET /admin/location_sites/new
  def new
    @admin_location_site = Admin::LocationSite.new
  end

  # GET /admin/location_sites/1/edit
  def edit
  end

  # POST /admin/location_sites
  # POST /admin/location_sites.json
  def create
    @admin_location_site = Admin::LocationSite.new(admin_location_site_params)

    respond_to do |format|
      if @admin_location_site.save
        format.html { redirect_to @admin_location_site, notice: 'Location site was successfully created.' }
        format.json { render :show, status: :created, location: @admin_location_site }
      else
        format.html { render :new }
        format.json { render json: @admin_location_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/location_sites/1
  # PATCH/PUT /admin/location_sites/1.json
  def update
    respond_to do |format|
      if @admin_location_site.update(admin_location_site_params)
        format.html { redirect_to @admin_location_site, notice: 'Location site was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_location_site }
      else
        format.html { render :edit }
        format.json { render json: @admin_location_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/location_sites/1
  # DELETE /admin/location_sites/1.json
  def destroy
    @admin_location_site.destroy
    respond_to do |format|
      format.html { redirect_to admin_location_sites_url, notice: 'Location site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_location_site
      @admin_location_site = Admin::LocationSite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_location_site_params
      params.require(:admin_location_site).permit(:location_id, :site_name, :site_url)
    end
end

app/views/admin/location_sites/_form.html.erb
<%= form_for(@admin_location_site) do |f| %>
  <% if @admin_location_site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_location_site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @admin_location_site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :site_name %><br>
    <%= f.text_field :site_name %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/location_sites/edit.html.erb
<h1>Editing admin_location_site</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_location_site %> |
<%= link_to 'Back', admin_location_sites_path %>

app/views/admin/location_sites/index.html.erb
<h1>Listing admin_location_sites</h1>

<table>
  <thead>
    <tr>
      <th>Admin location</th>
      <th>Site name</th>
      <th>Site url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_location_sites.each do |admin_location_site| %>
      <tr>
        <td><%= admin_location_site.location.display_name %></td>
        <td><%= admin_location_site.site_name %></td>
        <td><%= admin_location_site.site_url %></td>
        <td><%= link_to 'Show', admin_location_site %></td>
        <td><%= link_to 'Edit', edit_admin_location_site_path(admin_location_site) %></td>
        <td><%= link_to 'Destroy', admin_location_site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location site', new_admin_location_site_path %>

app/views/admin/location_sites/new.html.erb
<h1>New admin_location_site</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_location_sites_path %>

app/views/admin/location_sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @admin_location_site.location_id %>
</p>

<p>
  <strong>Site name:</strong>
  <%= @admin_location_site.site_name %>
</p>

<p>
  <strong>Site url:</strong>
  <%= @admin_location_site.site_url %>
</p>

<%= link_to 'Edit', edit_admin_location_site_path(@admin_location_site) %> |
<%= link_to 'Back', admin_location_sites_path %>